spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/postgres}
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:postgres}
    hikari:
      schema: users_schema
  jpa:
    show-sql: false
    properties:
      hibernate:
        format_sql: true

#logging:
#  level:
#    root: trace